QT.thelib.VERSION = 1.0
QT.thelib.MAJOR_VERSION = 1
QT.thelib.MINOR_VERSION = 1
QT.thelib.name = the-libs
QT.thelib.module = the-libs
QT.thelib.depends = core dbus
QT.thelib.includes = $$QT_MODULE_INCLUDE_BASE $$QT_MODULE_INCLUDE_BASE/the-libs/
QT.thelib.libs = $$QT_MODULE_LIB_BASE
QT_MODULES += thelib
