
THELIBS_INSTALL_PREFIX = PREFIX
equals(THELIBS_INSTALL_PREFIX, "") {
    THELIBS_INSTALL_PREFIX = $$[THELIBS_INSTALL_PREFIX]
}
equals(THELIBS_INSTALL_PREFIX, "") {
    THELIBS_INSTALL_PREFIX = $$[QT_INSTALL_PREFIX]
}
